### PR TITLE
Update mmg and adding libs and includes

### PR DESCRIPTION
**Pull request by loumalouomega**
Just that

### CODE REVIEW

**Comment by loumalouomega** [comment]
Fixes #2

**Comment by loumalouomega** [comment]
@oberbichler is this merged?

**Comment by oberbichler** [comment]
No. I think it's better if it's compiled within the container. This should avoid problems with different compilers etc. If you have special requirements, you must tell me.

Have a nice weekend!

**Comment by loumalouomega** [comment]
OK

**Pull request closed without merging**
